{"name": "test_vwo_login_positive", "status": "broken", "statusDetails": {"message": "RecursionError: maximum recursion depth exceeded", "trace": "setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"4864c03a4b1a63b69794800686250dfb\")>\n\n    @allure.epic(\"VWO Login Test\")\n    @allure.feature(\"TC#1 - VWO App Positive Test\")\n    @pytest.mark.positive\n    def test_vwo_login_positive(setup):\n        driver = setup\n        loginPage = LoginPage(driver)\n        loginPage.login_to_vwo(usr=\"py2x@thetestingacademy.com\", pwd=\"Wingify@1234\")\n        time.sleep(10)\n        dashboardPage=DashboardPage(driver)\n        assert \"Dashboard\" in driver.title\n>       assert \"Aman\" in dashboardPage.user_logged_in_text()\n\ntestcases_VWO_login.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pageObjects\\dashboardPage.py:18: in user_logged_in_text\n    return self.user_logged_in_text()\n..\\pageObjects\\dashboardPage.py:18: in user_logged_in_text\n    return self.user_logged_in_text()\nE   RecursionError: maximum recursion depth exceeded\n!!! Recursion detected (same locals & position)"}, "start": 1715827914620, "stop": 1715827925243, "uuid": "b5be1232-ec20-4ee2-8ce1-c8452588bf8e", "historyId": "66dc95d5e12947c6b49ffecd387acf0a", "testCaseId": "66dc95d5e12947c6b49ffecd387acf0a", "fullName": "tests.vwoLoginTests.testcases_VWO_login#test_vwo_login_positive", "labels": [{"name": "feature", "value": "TC#1 - VWO App Positive Test"}, {"name": "epic", "value": "VWO Login Test"}, {"name": "tag", "value": "positive"}, {"name": "parentSuite", "value": "tests.vwoLoginTests"}, {"name": "suite", "value": "testcases_VWO_login"}, {"name": "host", "value": "INDELNB1516"}, {"name": "thread", "value": "25988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vwoLoginTests.testcases_VWO_login"}]}